### ISSUE TITLE
It seems your class `_GrowableList<String>` has not been annotated with `@jsonSerializable`

### ISSUE THREAD

**Issue by peterweb2005** [k-paxian/dart-json-mapper#171] opened 2021-11-03 08:42 UTC
as title
development time is good

thanks

**Comment by k-paxian** [comment] 2021-11-03 08:48
Unfortunately, this tells me nothing. Can you provide a localized reproducible code snippet to illustrate the issue?

**Comment by peterweb2005** [comment] 2021-11-03 08:57
need much much times, but

is that related to this:

```
@jsonSerializable
@Json(
  ignoreNullMembers: true,
  valueDecorators: Test.valueDecorators,
)
class Test {
  //
  List<List<String>>? timetable;

  static Map<Type, ValueDecoratorFunction> valueDecorators() => {
        typeOf<List<List<String>>>(): (value) => value.cast<List<String>>(),
        typeOf<List<String>>(): (value) => value.cast<String>()
      };
}
```

**Comment by peterweb2005** [comment] 2021-11-03 09:04
screen capture stacktrace
https://ibb.co/S0vQVCT

**Comment by peterweb2005** [comment] 2021-11-03 09:18
quite sure the problem related to valueDecorators,

i just commented the field & related stuffs, generate files, build apk, install, run
the alert has not been displayed

**Comment by Groseuros** [comment] 2021-11-03 23:30
Hello,

First of all, thank you for your work !

I'm facing exactly the same issue with my **release build** for both iOS and Android (working fine in debug / profile mode).
Last working build was build Sept 30.

When I call `JsonMapper.serialize(mySuperClass)` I got this exception : **It seems your class '_GrowableList<anotherClass> has not been annotated with @JsonSerializable**.

I tried to downgrade `dart_json_mapper: ^2.1.16` to **^2.1.2**, `dart_json_mapper_flutter: ^2.0.1` to **^2.0.0** and `build_runner: ^2.1.4` to **^2.1.1** and regenerated mapper.g.dart file (my previous working build config) but the issue is still here.

I also tried to downgrade `Flutter v2.5.3` to **v2.5.2** and tried to build with `--no-shrink` flag but same result.

How can I help you to investigate ?

**Comment by k-paxian** [comment] 2021-11-04 10:55
Thank you both for reporting that 🤗 
I hope I'll have enough time to nail it down. Not promising it'll be blazingly fast, but it will be fixed anyway.

**Comment by Groseuros** [comment] 2021-11-04 12:39
Update:

I forgot to remove the '^' when I downgraded dart_json_mapper to 2.1.2 and and dart_json_mapper_flutter to 2.0.0.
I did it in the right way and it's working again.

I'll try each version tonight to figure out which one introduces the issue.

**Comment by Groseuros** [comment] 2021-11-04 21:48
Ok so... I can't upgrade package above v2.1.2 otherwise my app release build will trigger the exception, which sounds really strange to me.

Maybe I missed something with my config ?

**MainClass:**
```
@jsonSerializable
@Json(valueDecorators: MainClass.valueDecorators)
class MainClass {
  static Map<Type, ValueDecoratorFunction> valueDecorators() => {
        typeOf<List<OtherClassA>>(): (value) => value.cast<OtherClassA>(),
        typeOf<Map<String, List<OtherClassB>>>(): (value) =>
            value.cast<String, List<OtherClassB>>(),
        typeOf<List<OtherClassB>>(): (value) => value.cast<OtherClassB>()
      };

  List<OtherClassA> listOfClassA = [];
  Map<String, List<OtherClassB>> mapOfListsOfClassB =
      <String, List<OtherClassB>>{};

  Future<void> fillfromJson(Map<String, dynamic> json) async {
     ...
  }
}
```

**ClassA:**
```
@jsonSerializable
class ClassA {
  String name = '';
  int number = 0;

  void fillFromJson(Map<String, dynamic> json) {
    ...
  }
}
```

**ClassB:**
```
@jsonSerializable
class ClassB {
 [endless list of properties]

 [some methods]
}
```

**Comment by jiechic** [comment] 2021-11-11 07:36
it is same error on my release build

**Closed** 2021-11-19 18:36 UTC
Labels: bug, release.apk
